# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="team1_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bet",
            name="team2_name",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
    ]
