# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20170616_1514"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bet",
            old_name="game_id",
            new_name="game",
        ),
        migrations.RenameField(
            model_name="bet",
            old_name="user_id",
            new_name="user",
        ),
    ]
