# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170616_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='scheduled_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 22, 21, 14, 463399)),
        ),
    ]
