# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170617_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scheduled_datetime',
            field=models.DateTimeField(),
        ),
    ]
