# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 18:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20180607_1356"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("abbreviation", models.CharField(max_length=3)),
                ("flag", models.ImageField(upload_to="flags")),
            ],
        ),
        migrations.RenameField(
            model_name="bet",
            old_name="team1_score",
            new_name="away_score",
        ),
        migrations.RenameField(
            model_name="bet",
            old_name="team2_score",
            new_name="home_score",
        ),
        migrations.RemoveField(
            model_name="game",
            name="away",
        ),
        migrations.RemoveField(
            model_name="game",
            name="away_abbreviation",
        ),
        migrations.RemoveField(
            model_name="game",
            name="home_abbreviation",
        ),
        migrations.AlterField(
            model_name="game",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.Team"
            ),
        ),
    ]
