# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-09 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20180609_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
