# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_auto_20180611_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contests",
            field=models.ManyToManyField(related_name="contests", to="main.Contest"),
        ),
    ]
