# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-12 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180611_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='game',
        ),
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ManyToManyField(related_name='bets', to='main.Game'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
    ]
