# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 12:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_auto_20180612_1106"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="contest",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="main.Contest",
            ),
            preserve_default=False,
        ),
    ]
