# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-18 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_remove_team_flag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set([('user', 'game', 'contest')]),
        ),
    ]
