# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-30 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_auto_20180618_0949"),
        ("main", "0024_game_isplayoff"),
    ]

    operations = []
