# Generated by Django 5.2.15 on 2026-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_remove_profile_contests_alter_bet_away_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
