# Generated by Django 5.2.15 on 2026-06-14 08:42

import main.avatars
from django.db import migrations, models


def backfill_avatars(apps, schema_editor):
    """Make sure every user has a profile, each with its own random avatar
    (the column default would otherwise hand existing rows the same one)."""
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("main", "Profile")
    for user in User.objects.all():
        profile, created = Profile.objects.get_or_create(
            user=user, defaults={"avatar": main.avatars.random_key()}
        )
        if not created:
            profile.avatar = main.avatars.random_key()
            profile.save(update_fields=["avatar"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_profile_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.CharField(default=main.avatars.random_key, max_length=24),
        ),
        migrations.RunPython(backfill_avatars, migrations.RunPython.noop),
    ]
