# Generated by Django 5.2.15 on 2026-06-14 17:07

import main.avatars
from django.db import migrations, models


def reseed_avatars(apps, schema_editor):
    """Replace the old icon-key avatars with fresh DiceBear seeds so each
    profile gets its own distinct face."""
    Profile = apps.get_model("main", "Profile")
    for profile in Profile.objects.all():
        profile.avatar = main.avatars.random_seed()
        profile.save(update_fields=["avatar"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(default=main.avatars.random_seed, max_length=32),
        ),
        migrations.RunPython(reseed_avatars, migrations.RunPython.noop),
    ]
